add add_to_cluster command to mongooseimctl (sponsored by Grindr)

diff --git a/rel/files/mongooseim b/rel/files/mongooseim
--- a/rel/files/mongooseim
+++ b/rel/files/mongooseim
@@ -95,7 +95,39 @@ case "$1" in
             sleep 1
         done
         ;;
+    add_to_cluster)
+        NAME=$(echo $NAME_ARG | awk '{print $1}')
+        NODE=$(echo $NAME_ARG | awk '{print $2}')
+        NAME_TYPE=$(echo $NAME | sed 's/^\-//')
 
+        TARGETNODETOOL="$ERTS_PATH/escript $ERTS_PATH/nodetool $NAME $2 $COOKIE_ARG"
+        ADD_TO_CLUSTER_CMD="$ERTS_PATH/escript $ERTS_PATH/nodetool -exact_$NAME_TYPE $NODE $COOKIE_ARG add_to_cluster $2"
+
+        RES=`$NODETOOL ping`
+        if [ "$RES" = "pong" ]; then
+            echo "Error: Node is already running! Stop the node and delete Mnesia database directory."
+            exit 1
+        fi
+
+        MNESIA_DIR="$RUNNER_BASE_DIR/Mnesia.$NODE"
+        if [ -d "$MNESIA_DIR" ]; then
+            echo "Error: $MNESIA_DIR already exists. Please remove whole directory before continuing."
+            exit 1
+        fi
+        RES2=`$TARGETNODETOOL ping`
+        if [ "$RES2" = "pong" ]; then
+            RES3=`$ADD_TO_CLUSTER_CMD`
+            if [ "$RES3" = "ok" ]; then
+                echo "Node added to cluster. Run moongosectl live or mongooseclt start."
+            else
+                echo "Adding Node to cluster failed:  $RES3"
+                exit 1
+            fi
+        else
+            echo "Error: Node $2 is not reachable."
+            exit 1
+        fi
+        ;;
     restart)
         ## Restart the VM without exiting the process
         $NODETOOL restart
@@ -197,7 +229,7 @@ case "$1" in
         fi
         ;;
     *)
-        echo "Usage: $SCRIPT {start|stop|restart|reboot|ping|live|console|console_clean|attach|debug|version}"
+        echo "Usage: $SCRIPT {start|stop|restart|reboot|ping|live|console|console_clean|attach|debug|version|add_to_cluster}"
         exit 1
         ;;
 esac
